### ISSUE TITLE
Resolve Warnings in Documentation Generation on PHP 8.2 while Maintaining PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by shcherbanich** [bumble-tech/bumble-doc-gen#22]
When running the command `bumbleDocGen generate` under PHP 8.2, a few warnings are encountered. The objective is to resolve these warnings ensuring smooth functionality while keeping the codebase compatible with PHP 8.0. Here's how to proceed:

1. **Identify Warnings:**
   - Pinpoint the warnings encountered during the documentation generation process under PHP 8.2.

2. **Resolve Warnings:**
   - Address and fix the identified warnings ensuring that the functionality remains intact.

3. **Maintain Compatibility:**
   - Ensure that the changes made are backward compatible with PHP 8.0.

4. **Testing:**
   - Use PHPUnit to validate that the warnings have been resolved and the functionality is unaffected.
   - Run `composer run-script test` locally to confirm that all tests pass.

5. **Create Pull Request:**
   - Once the warnings are resolved and tested, create a pull request to the `1.x.x` branch with your fixes.
   - GitHub will automatically run your tests again when you create the pull request.

6. **Need Help?**
   - If you encounter any issues or require clarification on the process, feel free to comment on the issue, and a maintainer will assist you. 

By addressing these warnings, we aim to ensure that BumbleDocGen operates flawlessly under PHP 8.2 while maintaining compatibility with PHP 8.0.

**Comment by misantron** [comment]
Your code now is not compatible with PHP 8.2 because of using `ocramius/proxy-manager` which PHP version requirement is `php: ~8.0.0`. It's impossible to install dependencies via running `composer install` under PHP 8.2.

**Comment by shcherbanich** [comment]
Hello! As part of this task, we do not need to update dependencies, but only make sure that the code for generating documentation runs without warnings:
`./bin/bumbleDocGen generate` =>

`Deprecated: Use of "parent" in callables is deprecated in .../bumble-doc-gen/src/Core/Parser/Entity/Cache/CacheableEntityWrapperTrait.php on line 42`

It probably won't be difficult to fix this error

**Comment by shcherbanich** [comment]
I'm sorry, I understand what you're talking about. Let's look at a problem like preparing to migrate to a more modern version of PHP, because right now we don't have the right to opt out of `ocramius/proxy-manager`. You can install dependencies for php8.1 and run the library - documentation generation will work and the error can be fixed
