### ISSUE TITLE
Add Unit Tests for BumbleDocGen\Core\Configuration\ValueResolver Namespace

### ISSUE THREAD

**Issue by seanmcn** [bumble-tech/bumble-doc-gen#30]
To ensure the accuracy and reliability of the code within the `BumbleDocGen\Core\Configuration\ValueResolver` namespace, your contributions are essential. Here’s the process:

1. **Write Tests:**
   - Use PHPUnit to craft tests for all classes and methods in this namespace.
   - Ensure your tests are thorough and adhere to the existing testing conventions in the project.

2. **Run Tests Locally:**
   - Use `composer run-script test` to run the tests on your local machine and confirm they pass.

3. **Create Pull Request:**
   - Once you are ready, create a pull request to the `1.x.x` branch with your tests.
   - GitHub will automatically run your tests again when you create the pull request.

4. **Need Help?**
   - If you run into any issues or need further clarification, feel free to comment on the issue and a maintainer will provide assistance.

**Comment by praem90** [comment]
Can I work on this?

**Comment by seanmcn** [comment]
@praem90  that would be great, thanks, I've assigned you.
