### ISSUE TITLE
Add Unit Tests for BumbleDocGen\Core\Configuration\ValueTransformer Namespace

### ISSUE THREAD

**Issue by seanmcn** [bumble-tech/bumble-doc-gen#31]
It's essential to validate the code in the `BumbleDocGen\Core\Configuration\ValueTransformer` namespace to ensure its correctness and reliability. Here’s how you can contribute:

1. **Write Tests:**
   - Use PHPUnit to write tests for all classes and methods in this namespace.
   - Make sure the tests are comprehensive and follow the existing testing conventions in the project.

2. **Run Tests Locally:**
   - Use `composer run-script test` to run the tests on your local machine and ensure they pass.

3. **Create Pull Request:**
   - Once ready, create a pull request to the `1.x.x` branch with your tests.
   - GitHub will automatically run your tests again when you create the pull request.

4. **Need Help?**
   - If you encounter any issues or require assistance, comment on the issue and a maintainer will assist you.

**Comment by praem90** [comment]
Could you please assign me to this ticket?

**Comment by shcherbanich** [comment]
@praem90 Done, thank you for your contribution to the development of the project!
