### ISSUE TITLE
Add console command to get configuration params

### ISSUE THREAD

**Issue by shcherbanich** [bumble-tech/bumble-doc-gen#48]
**Describe the solution you'd like**
We have a standard console application (./bin/bumbleDocGen). It is necessary to add a command to it that will allow you to obtain certain data from the current configuration. For example, display a list of connected plugins or twig functions.
How I see it:
`./bin/bumbleDocGen configuration plugins` => Will display a list of plugins
`./bin/bumbleDocGen configuration language_handlers` => Will display a list of connected programming language handlers
etc...

**Additional context**
The configuration is stored here: **\BumbleDocGen\Core\Configuration\Configuration**
**Core/Configuration/defaultConfiguration.yaml** - This is the basic configuration file

**Comment by misantron** [comment]
Hello, assign issue to me please

**Comment by seanmcn** [comment]
@misantron done, thanks 😄
